vpc_azs                            = ["us-east-1a", "us-east-1b"]
vpc_cidr                           = "10.0.0.0/16"
private_subnets                    = ["10.0.1.0/24", "10.0.2.0/24"]
public_subnets                     = ["10.0.101.0/24", "10.0.102.0/24"]
enable_nat_gateway                 = true
single_nat_gateway                 = true
database_subnets                   = ["10.0.151.0/24", "10.0.152.0/24"]
create_database_subnet_group       = true
create_database_subnet_route_table = true
enable_dns_support                 = true
enable_dns_hostnames               = true